spring:
  application:
    name: item-service
  datasource:
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/item-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
